global:
  scrape_interval: 5s
  scrape_timeout: 2s

scrape_configs:
  - job_name: 'sample'
    static_configs:
      - targets: ['app1:3000', 'app2:3000']
        labels:
          group: 'prod'

      - targets: ['app3:3000']
        labels:
          group: 'dev'

  - job_name: 'gateway'
    scrape_interval: 2s
    static_configs:
      - targets: ['prometheus-pushgateway:9091']
