name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  check_packages:
    name: "Check packages"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Setup node"
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "npm"

      - name: "Install dependencies"
        run: |
          npm ci

      - name: "Test"
        run: |
          npm test

      - name: "Stop docker compose"
        if: always()
        run: docker compose down

